version: "3.9" 
services:
  web:
    build: web/.
    ports:
      - "5000:5000"
    links:
      - user
      - tasks
  user:
    build: user/.
    links:
      - mongo
  tasks:
    build: tasks/.
    links:
      - mongo
  mongo:
    image: mongo